### ISSUE TITLE
ProgressReporter errors out, in plugin_minitest_reporter_init': undefined method `io='

### ISSUE THREAD

**Issue by gaurish** [kern/minitest-reporters#170]
This is what I have in my test_helper.rb

```ruby
MiniTest::Reporters.use!(Minitest::Reporters::ProgressReporter,ENV,Minitest.backtrace_filter)
```

when I try to run this, I get the following error
```ruby
$ rake test:all                                                             
/Users/gaurish/.rvm/gems/ruby-2.2.2/gems/minitest-reporters-1.0.19/lib/minitest/minitest_reporter_plugin.rb:7:in `block in plugin_minitest_reporter_init': undefined method `io=' for Minitest::Reporters::ProgressReporter:Class (NoMethodError)
	from /Users/gaurish/.rvm/gems/ruby-2.2.2/gems/minitest-reporters-1.0.19/lib/minitest/minitest_reporter_plugin.rb:6:in `each'
	from /Users/gaurish/.rvm/gems/ruby-2.2.2/gems/minitest-reporters-1.0.19/lib/minitest/minitest_reporter_plugin.rb:6:in `plugin_minitest_reporter_init'
	from /Users/gaurish/.rvm/gems/ruby-2.2.2/gems/minitest-5.8.0/lib/minitest.rb:74:in `block in init_plugins'
	from /Users/gaurish/.rvm/gems/ruby-2.2.2/gems/minitest-5.8.0/lib/minitest.rb:72:in `each'
	from /Users/gaurish/.rvm/gems/ruby-2.2.2/gems/minitest-5.8.0/lib/minitest.rb:72:in `init_plugins'
	from /Users/gaurish/.rvm/gems/ruby-2.2.2/gems/minitest-5.8.0/lib/minitest.rb:123:in `run'
	from /Users/gaurish/.rvm/gems/ruby-2.2.2/gems/minitest-5.8.0/lib/minitest.rb:56:in `block in autorun'
	from /Users/gaurish/.rvm/gems/ruby-2.2.2/gems/spring-1.2.0/lib/spring/application.rb:156:in `fork'
	from /Users/gaurish/.rvm/gems/ruby-2.2.2/gems/spring-1.2.0/lib/spring/application.rb:156:in `serve'
	from /Users/gaurish/.rvm/gems/ruby-2.2.2/gems/spring-1.2.0/lib/spring/application.rb:131:in `block in run'
	from /Users/gaurish/.rvm/gems/ruby-2.2.2/gems/spring-1.2.0/lib/spring/application.rb:125:in `loop'
	from /Users/gaurish/.rvm/gems/ruby-2.2.2/gems/spring-1.2.0/lib/spring/application.rb:125:in `run'
	from /Users/gaurish/.rvm/gems/ruby-2.2.2/gems/spring-1.2.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/gaurish/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/gaurish/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

Rails 4.2.12
Minitest 5.8
Minitest reporters 1.0.19

**Comment by gaurish** [comment]
My bad. not really an issue. closing
