### ISSUE TITLE
JUnitReporter 1.2.0 parse_xml_for fails if the Minitest::Result source_location is not a file

### ISSUE THREAD

**Issue by awaltman** [kern/minitest-reporters#258]
Some of the tests in my application are dynamically generated at runtime. The tests pass successfully but when the reporter is run, I get errors like:  

 ```

/home/awaltman/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/pathname.rb:520:in `relative_path_from': different prefix: "" and "/home/awaltman/app" (ArgumentError)
        from /home/awaltman/.rvm/gems/ruby-2.4.3/gems/minitest-reporters-1.2.0/lib/minitest/reporters/junit_reporter.rb:75:in `parse_xml_for'
        from /home/awaltman/.rvm/gems/ruby-2.4.3/gems/minitest-reporters-1.2.0/lib/minitest/reporters/junit_reporter.rb:47:in `block (2 levels) in report'
        from /home/awaltman/.rvm/gems/ruby-2.4.3/gems/builder-3.2.3/lib/builder/xmlbase.rb:175:in `_nested_structures'
        from /home/awaltman/.rvm/gems/ruby-2.4.3/gems/builder-3.2.3/lib/builder/xmlbase.rb:68:in `tag!'
        from /home/awaltman/.rvm/gems/ruby-2.4.3/gems/builder-3.2.3/lib/builder/xmlbase.rb:93:in `method_missing'
        from /home/awaltman/.rvm/gems/ruby-2.4.3/gems/minitest-reporters-1.2.0/lib/minitest/reporters/junit_reporter.rb:46:in `block in report'
        from /home/awaltman/.rvm/gems/ruby-2.4.3/gems/minitest-reporters-1.2.0/lib/minitest/reporters/junit_reporter.rb:43:in `each'
        from /home/awaltman/.rvm/gems/ruby-2.4.3/gems/minitest-reporters-1.2.0/lib/minitest/reporters/junit_reporter.rb:43:in `report'
        from /home/awaltman/.rvm/gems/ruby-2.4.3/gems/minitest-reporters-1.2.0/lib/minitest/minitest_reporter_plugin.rb:26:in `each'
        from /home/awaltman/.rvm/gems/ruby-2.4.3/gems/minitest-reporters-1.2.0/lib/minitest/minitest_reporter_plugin.rb:26:in `report'
        from /home/awaltman/.rvm/gems/ruby-2.4.3/gems/minitest-5.11.3/lib/minitest.rb:808:in `each'
        from /home/awaltman/.rvm/gems/ruby-2.4.3/gems/minitest-5.11.3/lib/minitest.rb:808:in `report'
        from /home/awaltman/.rvm/gems/ruby-2.4.3/gems/minitest-5.11.3/lib/minitest.rb:141:in `run'
        from /home/awaltman/.rvm/gems/ruby-2.4.3/gems/minitest-5.11.3/lib/minitest.rb:63:in `block in autorun'
```
I think is because source_location is returning ["(eval)", 2].

An ugly workaround I've found is to replace:

```relative_path = file_path.relative_path_from(base_path)```

with:

```relative_path = file_path.exist? ? file_path.relative_path_from(base_path) : file_path```

in minitest-reporters-1.2.0/lib/minitest/reporters/junit_reporter.rb, but then the report xml files contain filepath="(eval)" which is not ideal.

This appears to be introduced by commit https://github.com/kern/minitest-reporters/commit/12e4b183e5bb506fe823a9915b9dabe1e276bdb3

**Comment by os97673** [comment]
I think the right way to solve this problem is to try to fix `#get_source_location` ( https://github.com/kern/minitest-reporters/blob/master/lib/minitest/reporters/junit_reporter.rb#L56-L62) to return file (if it is possible).  And if this is impossible: I'd suggest to skip filepath and lineno attrs.
Can you provide a test which reproduces the problem?

**Comment by awaltman** [comment]
Sure! Here is a test that reproduces the problem:
```
require 'test_helper'

class Eval
  class Test < ActiveSupport::TestCase
    def test_true
      assert true
    end

    [
      ["bool1", "true", "true"],
      ["bool2", "false", "false"]
    ].each do |a|
      (type, expectation1, expectation2) = a
      eval(%{
       def test_eval_#{type}_#{expectation1}
         assert_equal(#{expectation1}, #{expectation2})
       end
      })
    end
  end
end
```
Note that the test can randomly run without reporting the error -- I think it depends on the order the tests are run because one test method in this example does have a source location in the file.

**Comment by Gwendal35** [comment]
Hello, for information I had the same problem with 1.2.0 and it was solved after update to 1.3.0 .
I generate my report with single_file option.

**Comment by os97673** [comment]
@awaltman could you please check with 1.3.0 and reopen if it is still reproducible

**Comment by awaltman** [comment]
@os97673 I just tried with 1.3.0 and it is still an issue. I also tried using the single_file option to the JUnitReporter and saw the same problem. Could you please reopen this issue?

**Comment by os97673** [comment]
No problem.  I'm just surprised you didn't have ability to reopen the issue :(

**Comment by abarre** [comment]
I have the same issue on 1.3.0. So, I confirm the bug.

**Comment by kbrandwijk** [comment]
This is also an issue for me. I don't have any dynamic tests, it just always fails in 2.5.1.

**Comment by os97673** [comment]
@kbrandwijk please provide a test to reproduce the problem

**Comment by kbrandwijk** [comment]
test_helper.rb
```ruby
require 'minitest/reporters'

Minitest::Reporters.use! [Minitest::Reporters::JUnitReporter.new]
```

test/demo.rb
```
require 'test_helper'

class DemoTest < ActiveSupport::TestCase
  test "demo" do
 
    assert true
  end
end
```

output (anonymyzed):
```shell
Emptying /Users/*****/Development/github/*****/*****/test/reports
Writing XML reports to /Users/*****/Development/github/*****/*****/test/reports
Traceback (most recent call last):
	14: from /Users/*****/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest.rb:63:in `block in autorun'
	13: from /Users/*****/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest.rb:141:in `run'
	12: from /Users/*****/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest.rb:808:in `report'
	11: from /Users/*****/.rvm/gems/ruby-2.5.1/gems/minitest-5.11.3/lib/minitest.rb:808:in `each'
	10: from /Users/*****/.rvm/gems/ruby-2.5.1/gems/minitest-reporters-1.3.1/lib/minitest/minitest_reporter_plugin.rb:26:in `report'
	 9: from /Users/*****/.rvm/gems/ruby-2.5.1/gems/minitest-reporters-1.3.1/lib/minitest/minitest_reporter_plugin.rb:26:in `each'
	 8: from /Users/*****/.rvm/gems/ruby-2.5.1/gems/minitest-reporters-1.3.1/lib/minitest/reporters/junit_reporter.rb:44:in `report'
	 7: from /Users/*****/.rvm/gems/ruby-2.5.1/gems/minitest-reporters-1.3.1/lib/minitest/reporters/junit_reporter.rb:44:in `each'
	 6: from /Users/*****/.rvm/gems/ruby-2.5.1/gems/minitest-reporters-1.3.1/lib/minitest/reporters/junit_reporter.rb:47:in `block in report'
	 5: from /Users/*****/.rvm/gems/ruby-2.5.1/gems/builder-3.2.3/lib/builder/xmlbase.rb:93:in `method_missing'
	 4: from /Users/*****/.rvm/gems/ruby-2.5.1/gems/builder-3.2.3/lib/builder/xmlbase.rb:68:in `tag!'
	 3: from /Users/*****/.rvm/gems/ruby-2.5.1/gems/builder-3.2.3/lib/builder/xmlbase.rb:175:in `_nested_structures'
	 2: from /Users/*****/.rvm/gems/ruby-2.5.1/gems/minitest-reporters-1.3.1/lib/minitest/reporters/junit_reporter.rb:48:in `block (2 levels) in report'
	 1: from /Users/*****/.rvm/gems/ruby-2.5.1/gems/minitest-reporters-1.3.1/lib/minitest/reporters/junit_reporter.rb:69:in `parse_xml_for'
/Users/*****/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/pathname.rb:522:in `relative_path_from': different prefix: "" and "/Users/*****/Development/github/*****/*****" (ArgumentError)
```

**Comment by os97673** [comment]
will release 1.3.2.beta2 soon, please test
