### ISSUE TITLE
JUnitReporter v 1.2.0 parse_xml_for uninitialized constant Minitest ::Reporters::JUnitReporter::Pathname (NameError)

### ISSUE THREAD

**Issue by trabulmonkee** [kern/minitest-reporters#261]
Ran into the below error today after upgrading to minitest-reporters v 1.2.0

Environment:
Windows 7 x64
minitest 5.11.3
minitest-reporters 1.2.0

test file contents:
```
require 'rubygems'
gem 'minitest'
require 'minitest/reporters'
Minitest::Reporters.use! [Minitest::Reporters::JUnitReporter.new]
require 'minitest/autorun'

class MTR_Upgrade_Test < Minitest::Test

  def setup
    # do something begin
  end

  def teardown
    # do something end
  end

  def test_pass
    assert true, 'this should pass'
  end

  def test_fail
    assert false, 'this should fail'
  end

  def test_skip
    skip 'this should be skipped'
    assert false, 'this should not be reached'
  end

end # class
```
```
C:\temp\mtr>test_mtr_pathname_error.rb -v
Emptying C:/temp/mtr/test/reports
Writing XML reports to C:/temp/mtr/test/reports
C:/Ruby233-x64/lib/ruby/gems/2.3.0/gems/minitest-reporters-1.2.0/lib/minitest/re
porters/junit_reporter.rb:67:in `parse_xml_for': uninitialized constant Minitest
::Reporters::JUnitReporter::Pathname (NameError)
        from C:/Ruby233-x64/lib/ruby/gems/2.3.0/gems/minitest-reporters-1.2.0/li
b/minitest/reporters/junit_reporter.rb:48:in `block (2 levels) in report'
        from C:/Ruby233-x64/lib/ruby/gems/2.3.0/gems/builder-3.2.3/lib/builder/x
mlbase.rb:175:in `_nested_structures'
        from C:/Ruby233-x64/lib/ruby/gems/2.3.0/gems/builder-3.2.3/lib/builder/x
mlbase.rb:68:in `tag!'
        from C:/Ruby233-x64/lib/ruby/gems/2.3.0/gems/builder-3.2.3/lib/builder/x
mlbase.rb:93:in `method_missing'
        from C:/Ruby233-x64/lib/ruby/gems/2.3.0/gems/minitest-reporters-1.2.0/li
b/minitest/reporters/junit_reporter.rb:47:in `block in report'
        from C:/Ruby233-x64/lib/ruby/gems/2.3.0/gems/minitest-reporters-1.2.0/li
b/minitest/reporters/junit_reporter.rb:44:in `each'
        from C:/Ruby233-x64/lib/ruby/gems/2.3.0/gems/minitest-reporters-1.2.0/li
b/minitest/reporters/junit_reporter.rb:44:in `report'
        from C:/Ruby233-x64/lib/ruby/gems/2.3.0/gems/minitest-reporters-1.2.0/li
b/minitest/minitest_reporter_plugin.rb:26:in `each'
        from C:/Ruby233-x64/lib/ruby/gems/2.3.0/gems/minitest-reporters-1.2.0/li
b/minitest/minitest_reporter_plugin.rb:26:in `report'
        from C:/Ruby233-x64/lib/ruby/gems/2.3.0/gems/minitest-5.11.3/lib/minites
t.rb:808:in `each'
        from C:/Ruby233-x64/lib/ruby/gems/2.3.0/gems/minitest-5.11.3/lib/minites
t.rb:808:in `report'
        from C:/Ruby233-x64/lib/ruby/gems/2.3.0/gems/minitest-5.11.3/lib/minites
t.rb:141:in `run'
        from C:/Ruby233-x64/lib/ruby/gems/2.3.0/gems/minitest-5.11.3/lib/minites
t.rb:63:in `block in autorun'
```
I was able to solve this locally by adding require 'pathname' at the top of junit_reporter.rb

**Comment by trabulmonkee** [comment]
I don't see Pathname being used any where else within the repo/project so the require 'pathname' in the junit_reporter.rb seems appropriate.

**Comment by os97673** [comment]
Looks reasonable, I suspect we get pathname from fileutils is we are on Linux.  Unfortunately I do not have access to Windows could you please create a PR this way you will test it on Windows and I on Mac&Linux.
