### ISSUE TITLE
After running `rake reset_statistics`, Minitest::Reporters::MeanTimeReporter breaks Minitest

### ISSUE THREAD

**Issue by jdickey** [kern/minitest-reporters#271]
The [`:reset_statistics` Rake task](https://github.com/kern/minitest-reporters/blob/master/Rakefile#L56-L61) from the project Rakefile is mentioned numerous times in the source for [`Minitest::Reporters::MeanTimeReporter`](https://github.com/kern/minitest-reporters/blob/master/lib/minitest/reporters/mean_time_reporter.rb) as doing what it says, and the Rake task itself looks too simple to fail.

However, after running the Rake task and then running `rake`, I see the following error output:

```
gemset/gems/minitest-reporters-1.3.5/lib/minitest/reporters/mean_time_reporter.rb:251:in `block in create_or_update_previous_runs!': undefined method `[]' for false:FalseClass (NoMethodError)
	from .../minitest-reporters-1.3.5/lib/minitest/reporters/mean_time_reporter.rb:250:in `each'
	from .../minitest-reporters-1.3.5/lib/minitest/reporters/mean_time_reporter.rb:250:in `create_or_update_previous_runs!'
	from .../minitest-reporters-1.3.5/lib/minitest/reporters/mean_time_reporter.rb:79:in `report'
	from .../minitest-reporters-1.3.5/lib/minitest/minitest_reporter_plugin.rb:26:in `each'
	from .../minitest-reporters-1.3.5/lib/minitest/minitest_reporter_plugin.rb:26:in `report'
	from .../minitest-5.11.3/lib/minitest.rb:808:in `each'
	from .../minitest-5.11.3/lib/minitest.rb:808:in `report'
	from .../minitest-5.11.3/lib/minitest.rb:141:in `run'
	from .../minitest-tagz-1.6.0/lib/minitest/tagz.rb:56:in `run'
	from .../minitest-5.11.3/lib/minitest.rb:63:in `block in autorun'

# Running tests with run options --seed 62125:

.........

Finished tests in 0.002525s, 3564.3564 tests/s, 3564.3564 assertions/s.


9 tests, 9 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for Unit Tests to .../tmp/coverage. 26 / 26 LOC (100.0%) covered.
rake aborted!
Command failed with status (1)

Tasks: TOP => default => test
(See full trace by running task with --trace)
```

If I run the specs using *any other reporter*, there's no problem.

How to reset statistics safely for `MeanTimeReporter`?

**Comment by itsliamegan** [comment]
Fixed by #296
