### ISSUE TITLE
Output file too long

### ISSUE THREAD

**Issue by coding-bunny** [kern/minitest-reporters#282]
Hello,

my test-suite is running into the following problem:

```
Writing XML reports to /root/rails_backend/test/reports
/root/rails_backend/vendor/bundle/ruby/2.2.0/gems/minitest-reporters-0.14.24/lib/minitest/reporters/junit_reporter.rb:42:in `initialize': File name too long @ rb_sysopen - /root/rails_backend/test/reports/TEST-DropShipmentObserverTest-Given-an-order-when-it-is-a-campaign-order-with-drop-shipment-when-campaign-data-exists-and-fulfillment-change-is-called-when-the-order-has-Represent-fulfillment-source-and-is-assigned-to-non-european-vendor-wh.xml (Errno::ENAMETOOLONG)
	from /root/rails_backend/vendor/bundle/ruby/2.2.0/gems/minitest-reporters-0.14.24/lib/minitest/reporters/junit_reporter.rb:42:in `open'
	from /root/rails_backend/vendor/bundle/ruby/2.2.0/gems/minitest-reporters-0.14.24/lib/minitest/reporters/junit_reporter.rb:42:in `block in after_suites'
	from /root/rails_backend/vendor/bundle/ruby/2.2.0/gems/minitest-reporters-0.14.24/lib/minitest/reporters/junit_reporter.rb:27:in `each'
	from /root/rails_backend/vendor/bundle/ruby/2.2.0/gems/minitest-reporters-0.14.24/lib/minitest/reporters/junit_reporter.rb:27:in `after_suites'
	from /root/rails_backend/vendor/bundle/ruby/2.2.0/gems/minitest-reporters-0.14.24/lib/minitest/reporter_runner.rb:97:in `public_send'
	from /root/rails_backend/vendor/bundle/ruby/2.2.0/gems/minitest-reporters-0.14.24/lib/minitest/reporter_runner.rb:97:in `block in trigger_callback'
	from /root/rails_backend/vendor/bundle/ruby/2.2.0/gems/minitest-reporters-0.14.24/lib/minitest/reporter_runner.rb:97:in `each'
	from /root/rails_backend/vendor/bundle/ruby/2.2.0/gems/minitest-reporters-0.14.24/lib/minitest/reporter_runner.rb:97:in `trigger_callback'
	from /root/rails_backend/vendor/bundle/ruby/2.2.0/gems/minitest-reporters-0.14.24/lib/minitest/reporter_runner.rb:39:in `_run_suites'
	from /root/rails_backend/vendor/bundle/ruby/2.2.0/gems/minitest-4.7.5/lib/minitest/unit.rb:877:in `_run_anything'
	from /root/rails_backend/vendor/bundle/ruby/2.2.0/gems/minitest-4.7.5/lib/minitest/unit.rb:1085:in `run_tests'
	from /root/rails_backend/vendor/bundle/ruby/2.2.0/gems/minitest-reporters-0.14.24/lib/minitest/reporter_runner.rb:30:in `run_tests'
	from /root/rails_backend/vendor/bundle/ruby/2.2.0/gems/minitest-4.7.5/lib/minitest/unit.rb:1072:in `block in _run'
	from /root/rails_backend/vendor/bundle/ruby/2.2.0/gems/minitest-4.7.5/lib/minitest/unit.rb:1071:in `each'
	from /root/rails_backend/vendor/bundle/ruby/2.2.0/gems/minitest-4.7.5/lib/minitest/unit.rb:1071:in `_run'
	from /root/rails_backend/vendor/bundle/ruby/2.2.0/gems/minitest-4.7.5/lib/minitest/unit.rb:1059:in `run'
	from /root/rails_backend/vendor/bundle/ruby/2.2.0/gems/minitest-4.7.5/lib/minitest/unit.rb:795:in `block in autorun'
```

Is there any way to overwrite the behavior to either write everything in a single file and set the name?

**Comment by os97673** [comment]
There is no such option and (honestly) I'm not sure there is a way to provide good enough generic algorithm for this.  I'd suggest either rename the test or create subclass of the reporter to make it works for your particular suite.  (and as always: PRs are welcome ;) )
